config/routes.rb
Rails.application.routes.draw do
  resources :enquiries

  resources :static_pages

  root 'static_pages#index'

  match "/about-us", to: "static_pages#about_us", via: "get"

  match "/accreditations", to: "static_pages#accreditations", via: "get"

  match "/products", to: "static_pages#products", via: "get"

  match "/projects", to: "static_pages#projects", via: "get"

  match "/contact-us", to: "enquiries#index", via: "get"

end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  before_action :set_enquiry, only: [:show, :edit, :update, :destroy]

  # GET /enquiries
  def index
    @enquiries = Enquiry.all
  end

  # GET /enquiries/1
  def show
  end

  # GET /enquiries/new
  def index
    @enquiry = Enquiry.new
  end

  # GET /enquiries/1/edit
  def edit
  end

  # POST /enquiries
  def create
    @enquiry = Enquiry.new(enquiry_params)

    if @enquiry.save
      redirect_to @enquiry, notice: 'Enquiry was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /enquiries/1
  def update
    if @enquiry.update(enquiry_params)
      redirect_to @enquiry, notice: 'Enquiry was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /enquiries/1
  def destroy
    @enquiry.destroy
    redirect_to enquiries_url, notice: 'Enquiry was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enquiry
      @enquiry = Enquiry.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def enquiry_params
      params.require(:enquiry).permit(:name, :email, :body)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_static_page, only: [:show, :edit, :update, :destroy]

  # GET /static_pages
  def index
    @static_pages = StaticPage.all
  end

  # GET /static_pages/1
  def show
  end

  # GET /static_pages/new
  def new
    @static_page = StaticPage.new
  end

  # GET /static_pages/1/edit
  def edit
  end

  # POST /static_pages
  def create
    @static_page = StaticPage.new(static_page_params)

    if @static_page.save
      redirect_to @static_page, notice: 'Static page was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /static_pages/1
  def update
    if @static_page.update(static_page_params)
      redirect_to @static_page, notice: 'Static page was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /static_pages/1
  def destroy
    @static_page.destroy
    redirect_to static_pages_url, notice: 'Static page was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static_page
      @static_page = StaticPage.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def static_page_params
      params[:static_page]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/enquiries/_form.html.haml
= form_for(@enquiry) do |f|
  - if @enquiry.errors.any?
    #error_explanation
      %h2
        = pluralize(@enquiry.errors.count, "error")
        prohibited this enquiry from being saved:
      %ul
        - @enquiry.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :body, 'Enquiry'
    %br/
    = f.text_area :body
  .actions_buuton
    = f.submit'Submit'

app/views/enquiries/edit.html.erb
<h1>Editing enquiry</h1>

<%= render 'form' %>

<%= link_to 'Show', @enquiry %> |
<%= link_to 'Back', enquiries_path %>

app/views/enquiries/index.html.haml
.content 
  .column.split_5
    .head_text
      %h1 contact
      %h2 If you have any enquiries then do not hesitate to contact us on the details below or using the form on the right.
    .contact_information_enquiry
      %p Tel: 01508 530004<br>Fax: 01508 536006Address:<br> 
      %p Unit 14, Salamanca Road,<br>Tharston Industrial Estate,<br>Long Stratton,<br>Norwich,<br>NR15 2PF<br>
  .enquiry_form.column.split_5
    = render 'enquiries/form'

app/views/enquiries/new.html.erb
<h1>New enquiry</h1>

<%= render 'form' %>

<%= link_to 'Back', enquiries_path %>

app/views/enquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @enquiry.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @enquiry.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @enquiry.body %>
</p>

<%= link_to 'Edit', edit_enquiry_path(@enquiry) %> |
<%= link_to 'Back', enquiries_path %>

app/views/layouts/_footer.html.haml
.footer_outer.clearfix
  .content
    .footer
      %p &copy; Symphony Windows Ltd. 2013. All rights reserved.<br>Company Reg.: 3591365. CE Marking<br>Registered Office : Bankside 300, Peachman Way, Broadland Business Park, Norwich , NR7 0LB #{link_to 'Web Design Norwich', 'http://cd2solutions.co.uk/' }

app/views/layouts/_header.html.haml
.header.clearfix
  .content
    .logo
      = link_to image_tag('logo.png'), root_path 
    .nav
      %ul 
        %li= link_to 'Home', root_path
        %li= link_to 'Products and Services', products_path
        %li= link_to 'Projects', projects_path
        %li= link_to 'Accreditations', accreditations_path
        %li= link_to 'About Us', about_us_path
        %li= link_to 'Contact Us', contact_us_path

app/views/layouts/_header_home.html.haml
.home_header_wrapper
  .content
    .nav
      %ul 
        %li= link_to 'Home', root_path
        %li= link_to 'Products and Services', products_path
        %li= link_to 'Projects', projects_path
        %li= link_to 'Accreditations', accreditations_path
        %li= link_to 'About Us', about_us_path
        %li= link_to 'Contact Us', contact_us_path
    .home_header
      = image_tag('log.png')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Symphony
    %script{:src => "//use.typekit.net/fgj6smy.js"}
    :javascript
      try{Typekit.load();}catch(e){}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .general_wrap
      - if request.fullpath == root_path
        = render 'layouts/header_home'
      - else
        = render 'layouts/header'
      = yield
      = render 'layouts/footer'

app/views/static_pages/about_us.html.haml
.content
	.head_text.column.split_4
		%h1 About Us
		%h2 Symphony Windows is a family run business based in the Norfolk area, proud to be suppling you with the best
	.about_columns.column.split_10
		.column.split_25
			= image_tag('about-1.jpg')
			%h3 History
			%p Symphony Windows Limited was formed in 1998 and we have built our success around the philosophy of being flexible to respond to clients needs, together with an enlightened approach to problem solving.
			%p We pride ourselves on completing projects quickly, efficiently and to a high standard of workmanship, which combined with a non-adversarial approach, ensures each scheme is completed on time, within budget and in a manner that turns the whole process into a rewarding experience for all concerned.
		.column.split_25
			= image_tag('about-2.jpg')
			%h3 Forward Thinking
			%p Now considered a large commercial installation operation, often installing in excess of five hundred frames a week, it has been essential that all areas of the business have been able to cope with this expansion and for that reason the company sought and gained total quality service backed by BS EN ISO 9001:2008 accreditation.
			%p Couple this with our excellent safety record, together with a reliable, pro-active and motivated approach to work as can be expected of a forward thinking company.
		.column.split_25
			= image_tag('about-3.jpg')
			%h3 Trusted
			%p As you would expect, a company listed  on so many local authority approved lists would need to prove and demonstrate its ability to undertake projects within its field and for this reason Symphony secured registration within Constructionline, created and owned by the Department of the Environment, Transport, and the regions.  Following the introduction of part L to the building regulations upgrade, Symphony became a member of FENSA, which enables us to offer our client base the ability to self-certify compliance without the need to obtain building regulations approval. In addition we are included in EXOR listings, a Government body which vets window installers for their capabilities.
		.column.split_25
			= image_tag('about-4.jpg')
			%h3 Proud
			%p Symphony is proud of the safety track record within the company, which has been brought about by a broad knowledge within the company, supported by an external consultancy that oversee any anomalies which may occur on site. Our workforce is kept fully appraised of risks on site, and any changes to working methods and practical guidelines. We have gained the British Standard for fitting/installaion of windows and now carry he quality assured Kitemark.  We are pleased to be recognised as part of SAFECONTRACTOR who regularly check that we are up to date on Health and Safety matters

app/views/static_pages/accreditations.html.haml
.content
  .head_text.column.split_4 
    %h1 Accreditations
    %h2 Always pushing to have the best<br>standards
  .top_right_buffer.column.split_6
    = link_to 'PAS2030', root_path
  .column.split_10 
    .column.split_2
      = image_tag('k1.jpg')
    .column.split_2
      = image_tag('k2.jpg')
    .column.split_2
      = image_tag('k3.jpg')
    .column.split_2
      = image_tag('k4.jpg')
    .column.split_2
      = image_tag('sec.jpg')
    .column.split_2
      = image_tag('ggf.jpg')
    .column.split_2
      = image_tag('safecon.jpg')
    .column.split_2
      = image_tag('fansa.jpg')
    .column.split_2
      = image_tag('concline.jpg')
    .column.split_2
      = image_tag('bsi-is0-9001-small.jpg')
    .column.split_2
      = image_tag('CE.png')
    .column.split_2
      = image_tag('greendeal.png')

app/views/static_pages/index.html.haml
.content
	.homepage 
		.summary_header.column.split_10
			%p Specialist suppliers, installers and manufacturers of
		.column.split_4
			.column.split_10
				%h1 <span class="section_one">PVCu</span> <span>&amp;</span> <span class="section_one">Aluminium</span><br><span>Windows</span> &amp;</span> <span>Doors</span>
			.four_grid.column.split_10
				.block_one.column.split_4
					%p Products and Services
				.block_two.column.split_4
					%p Projects
				.block_three.column.split_4
					%p Accreditations
				.block_four.column.split_4
					%p About Us
		.column.split_6
			.home_information	
				%p Symphony Windows specialises in the supply and installation of PVCu + Aluminium windows and doors for predominantly public sector property, including social housing, educational establishment and public buildings. Offering a vast range of Products and Services to meet their clients every need, supplying and installing windows from the top manufacturing brands available.
				%p Symphony is proud of the safety track record within the company, which has been brought about by a broad knowledge within the company, supported by an external consultancy that oversee any anomalies which may occur on site.
			.contact_info
				%p If you have any enquiries then do not<br>hesitate to get in touch either on our contact<br>us page or by using the contact numbers<br>below:
				%h2 TEL: 01508 530004
				%h3 enquiries@symphonywindows.co.uk

app/views/static_pages/products.html.haml
.content
	.head_text.column.split_4
		%h1 Products &amp; Services
		%h2 At Symphony we belive in<br>Providing maximum client<br>satisfaction and value for money.
	.top_right_buffer.column.split_6
		%p A major advantage to our client base is the ability to offer a choice of quality profiles within our PVCu range and our aluminium manufacturing range. We also offer a range of Composite doors & Composite fire which have, PAS O23/O24 and Secure by design.
		%p As well as a wide range of products we also offer an extesive range of services.  These services include:
		%ul 
			%li Involvement in feasibility studies to provide essential information for the specifications, data on performance and help Clients choose the best system for the project
			%li Provide an estimating service producing budget costs, cash flow forecasts and cost comparisons to aid choice and predictability
			%li Design and drawing services
			%li Programming advice - having had first hand knowledge of time constraints of all the components of the supply chain
			%li Trial installation and/or on site investigation service to identify problems and site conditions, prior to project commencement.  This can include lintel and structural problems, asbestos issues, Health and Safety issues, the choice of fixing and installation methods and the requirements of residents
			%li Attendance to residents meetings at any stage to listen to views, answer questions and keep them fully informed
	.products_row.column.split_10
		.column.split_3
			= image_tag('alum-prev.jpg')
			%h2 Aluminium
			%p We specialise in the manufacture and supply of Sapa and Smart glazing system products but can source and supply any glazing system you may require.
		.column.split_3
			= image_tag('pvc-prev.jpg')
			%h2 PVC
			%p We are able to offer quality profiles including Rehau, Veka, Kommerling and Profile 22 within our PVCu range
		.column.split_3
			= image_tag('manu-prev.jpg')
			%h2 Manufacturing
			%p Our modern factory houses some of the latest Elumatec machinery including CNC saws and machines, thus assuring you perfect accuracy and consistency in the machining of the product combined with trained staff working to BS4875 and PAS23, bringing you the best products available today.

app/views/static_pages/projects.html.haml
.content
	.head_text.column.split_4
		%h1 Projects
		%h2 Some of our recent work which we are most proud of
	.top_right_buffer.column.split_6
		%p We operate mainly in the London and South East area and pride ourselves on our attention to detail and overall quality from manufacture to installation
	.project_cards.column.split_10
		.project_card.column.split_3
			%h3 Blenheim Court, Islington
			%h4 Client : Homes for Islington, Contractor : Apollo London Ltd
			= image_tag('Blenheim_court.jpg')
			%p Overview - This was a window and door replacement scheme that took place between April and September 2006 where we acted as a sub-contractor working for the clients appointed main contractor.<br>Complete replacements were required to the majority of the 122 flats contained within the project....
		.project_card.column.split_3
			%h3 Cunningham Close, Romford
			%h4 Client : Home Group Ltd
			= image_tag('Cunningham.jpg')
			%p Overview - This was an external cladding window and door replacement project that we carried out between September and December 2006 where we worked directly as the main contractor for our client, Home Group. It was a sheltered housing scheme of 54 properties plus communal areas. We worked...
		.project_card.column.split_3
			%h3 Rennie Estate, Rotherhithe
			%h4 Contractor : Apollo London Ltd, Client : London Borough of Southwark
			= image_tag('Rennie_Est.jpg')
			%p Overview - This was an aluminium window and door replacement project that we carried out between March and July 2006 where we worked as a subcontractor to the appointed main contractor. There were 67 flats spread over 4 blocks plus communal stairwell areas. The scheme was completed on time and...